export const customStylesModal = {
	overlay: {
		bacgroundColor: 'rgba(142, 154, 175, 0.8)',
		zIndex: 1500,
	},
	content: {
		position: 'absolute',
		top: '50%',
		left: '50%',
		zIndex: 1200,
		right: 'auto',
		bottom: 'auto',
		marginRight: '-50%',
		transform: 'translate(-50%, -50%)',
		maxWidth: '100%',
		width: '480px',
		height: '520px',
		boxShadow: '2px 2px 2px #0f0f0f',
		border: 'none',
		borderRadius: 'none',
		bacgroundColor: '#ebecf0',
		color: '#434343',
		textShadow: '1px 4px 6px #a8abb7, 1px -2px 2px #fff',
	},
};

export const customStylesInsideModal = {
	overlay: {
		bacgroundColor: 'rgba(142, 154, 175, 0.8)',
		zIndex: 1501,
	},
	content: {
		position: 'absolute',
		top: '50%',
		left: '50%',
		zIndex: 1201,
		right: 'auto',
		bottom: 'auto',
		marginRight: '-50%',
		transform: 'translate(-50%, -50%)',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		gap: '8px',
		maxWidth: '100%',
		width: '480px',
		height: '520px',
		boxShadow: '2px 2px 2px #0f0f0f',
		border: 'none',
		borderRadius: 'none',
		bacgroundColor: '#ebecf0',
		color: '#434343',
		textShadow: '1px 4px 6px #a8abb7, 1px -2px 2px #fff',
	},
};